module.exports = {
    SHOW_CART: 'SHOW_CART',
    SHOW_ORDER_ITEM_FORM: 'SHOW_ORDER_ITEM_FORM',
    SHOW_NEW_PRODUCT_FORM: 'SHOW_NEW_PRODUCT_FORM',
    SEARCH_PRODUCT: 'SEARCH_PRODUCT',
    SAVE_NEW_PRODUCT: 'SAVE_NEW_PRODUCT',
    ADD_ORDER_ITEM_ADD: 'ADD_ORDER_ITEM',
    REPLACE_ORDER_ITEM: 'REPLACE_ORDER_ITEM',
    REMOVE_ORDER_ITEM: 'REMOVE_ORDER_ITEM',
    CHANGE_VIEW_MODE: 'CHANGE_VIEW_MODE',
    MESSAGE_ADD:  'MESSAGE_ADD'
};